### ISSUE TITLE
Erro ao compilar release 1.0.2 (e545759)

### ISSUE THREAD

**Issue by brunohass** [bzlcoin/bzlcoin#1]
No arquivo net.cpp, linha 1302, falta uma vírgula.

Testado com o arquivo para download em tar.gz (https://github.com/bzlcoin/bzlcoin/archive/v1.0.2.tar.gz), fazendo clone do repositório não gera erro.

Abraço!

**Comment by bzlcoin** [comment]
Hola,
Sim, de fato já havíamos observado que a correção não saiu na release.
Já excluirmos a release e a recriamos, porem mesmo assim a release continua colocando o arquivo antigo.
Estamos abrindo um chamado no Git para verificar oque acontece.
Enquanto isso inserimos o bzlcoin-master.zip dentro da release, ele tem o código correto. 

Abraço!

**Comment by bzlcoin** [comment]
Solucionado com a versão 2.0
