### ISSUE TITLE
permanet crash of bzlcoind on Linux Ubuntu

### ISSUE THREAD

**Issue by djspacedevil** [bzlcoin/bzlcoin#2]
Hey, 

i run the deamon on Linux, Ubuntu 14. but it crash every 5 min, without a error message.
The deamon dont run stabile... can you check that, or can anybody confirm that?

**Comment by brminer** [comment]
Can you attach your bzlcoin.conf from ~/.bzlcoin/ folder ?

**Comment by djspacedevil** [comment]
`
daemon=1
server=1
rpcuser=user
rpcpassword=password
rpcallowip=127.0.0.1
rpcallowip=172.17.0.2
rpcallowip=172.17.42.1
rpcport=7771
port=27777
datadir=/opt/multipools/wallets/BZLCoin
whiteconnections=4
whitelist=127.0.0.1
forcednsseed=1
gen=0
blocknotify=sh -c "/opt/multipools/blocknotify 127.0.0.1:3360 2042 --block %s --password t"
onlynet=ipv4
addnode=100.1.150.31:27777
addnode=121.114.106.137:27777
addnode=152.208.105.61:27777
addnode=176.31.13.198:27777
addnode=176.9.156.236:27777
addnode=179.199.201.172:27777
addnode=189.71.210.62:27777
addnode=35.189.70.120:27777
addnode=67.207.89.186:27777
addnode=88.135.220.26:27777
addnode=94.61.138.85:27777
addnode=95.85.34.235:27777
`

**Comment by Estb** [comment]
I see that your file has commands not supported in BZL.
Please see this documentation, the supported commands.

https://github.com/bzlcoin/bzlcoin/blob/07ab2d2f8b59382286e4e36202b49c983202e896/contrib/debian/manpages/bzlcoin.conf.5

**Comment by djspacedevil** [comment]
Hy,

problem solved. It crashed only on complete chain sync. From 0% to 100% every 5 min.
Now, the chain is loaded an it runs, stable, first of all.
